### ISSUE TITLE
Can you provide a Raspberry Pi version of DIY OOD

### ISSUE THREAD

**Issue by waterflier** [buckyos/CYFS#94]
**The purpose of the feature**
Run DIY OOD on Reaspbeery Pi~

**Comment by lurenpluto** [comment]
Need to buy a Raspberry Pi device to test, it should be supported in theory

**Comment by weiqiushi** [comment]
Test platform: Raspberry Pi 4B

No need to modify the code, you can compile the OOD Service program which run on the Raspberry Pi hardware, it has been manually compiled and run through

Compilation steps:
1. install the latest stable version of rust
2. `rustup target add aarch64-unknown-linux-gnu` to add the cross-compiled library of rust
3. Prepare the cross-compilation tool for Raspberry Pi
4. Edit the `~/.cargo/config`(linux) or `%USERPROFILE%\.cargo\config`(windows) file to add the cross-compilation chain information of aarch64-unknown-linux-gnu
    ```toml
    [target.aarch64-unknown-linux-gnu]
    linker = "gcc path to the cross-compilation chain"
    ar = "path to ar for the cross-compilation chain" ```
5. configure environment variables
    ```
    CC_aarch64-unknown-linux-gnu = "gcc path of the cross-compilation chain"
    AR_aarch64-unknown-linux-gnu="ar path of the cross-compilation chain"
    ```
6. checkout code from https://github.com/buckyos/CYFS
7. In the src directory, execute in order
   ```
        cargo build -p gateway --release
        cargo build -p app-manager --release
        cargo build -p file-manager --release
        cargo build -p chunk-manager --release
   ```
   OOD Service required for compilation

The official, earliest version of the compilation chain gcc-arm-9.2-2019.12-mingw-w64-i686-aarch64-none-linux-gnu depends on GLIBC version 2.32, while the Raspberry Pi OS comes with GLIBC version 2.31, the official compiled OOD Service cannot be run directly on the Raspberry Pi OS directly

Install Ubuntu 20 on Raspberry Pi, you can run the compiled OOD Service

Translated with www.DeepL.com/Translator (free version)
